/* Generated By:JavaCC: Do not edit this line. PascalParserTreeConstants.java Version 5.0 */
package net.unikernel.jccparser;

public interface PascalParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTPROG = 1;
  public int JJTVAR_LIST = 2;
  public int JJTTYPE = 3;
  public int JJTID_LIST = 4;
  public int JJTSTMT_LIST = 5;
  public int JJTSTMT = 6;
  public int JJTNUMERIC_VAL = 7;
  public int JJTEXP = 8;
  public int JJTFOR_INDEX_EXP = 9;
  public int JJTBODY = 10;


  public String[] jjtNodeName = {
    "parse",
    "prog",
    "var_list",
    "type",
    "id_list",
    "stmt_list",
    "stmt",
    "numeric_val",
    "exp",
    "for_index_exp",
    "body",
  };
}
/* JavaCC - OriginalChecksum=cf0b2b888b4f9815db5b5bff8de55df0 (do not edit this line) */
