/* Generated By:JJTree&JavaCC: Do not edit this line. PascalParserConstants.java */
package net.unikernel.jccparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PascalParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MULTI = 3;
  /** RegularExpression Id. */
  int LPAREN = 4;
  /** RegularExpression Id. */
  int RPAREN = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int DOT = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int MULTIPLY = 12;
  /** RegularExpression Id. */
  int DIVIDE = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int PROGRAM = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int INTEGER = 18;
  /** RegularExpression Id. */
  int REAL = 19;
  /** RegularExpression Id. */
  int BEGIN = 20;
  /** RegularExpression Id. */
  int END = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int TO = 23;
  /** RegularExpression Id. */
  int DO = 24;
  /** RegularExpression Id. */
  int DOWNTO = 25;
  /** RegularExpression Id. */
  int WRITE = 26;
  /** RegularExpression Id. */
  int WRITELN = 27;
  /** RegularExpression Id. */
  int READ = 28;
  /** RegularExpression Id. */
  int READLN = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int DIGITS = 34;
  /** RegularExpression Id. */
  int SIGN = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<MULTI_LINE_COMMENT>",
    "<MULTI>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "<ASSIGN>",
    "\"program\"",
    "\"var\"",
    "\"integer\"",
    "\"real\"",
    "\"begin\"",
    "\"end\"",
    "\"for\"",
    "\"to\"",
    "\"do\"",
    "\"downto\"",
    "\"write\"",
    "\"writeln\"",
    "\"read\"",
    "\"readln\"",
    "<ID>",
    "<LETTER>",
    "<NUMBER>",
    "<DIGIT>",
    "<DIGITS>",
    "<SIGN>",
  };

}
